defaults:
  - meta_base

name: leo
n_task: 4
task_update_num: 1

inner_update_step: 5

# leo specific 
l2_penalty_coef: 1.0e-8
kl_coef: 0.001
orthogonality_penalty_coef: 0.1
encoder_penalty_coef: 1.0e-9



leo_inner_lr: 0.01

# LEO (as in MAML) reqires special gradient updates in backbone
fast_weight: True

# For instantiate API
cls:
  _target_: methods.leo.LEO
  n_task: ${method.n_task}
  task_update_num: ${method.task_update_num}
  inner_lr: ${method.leo_inner_lr}
  inner_update_step: ${method.inner_update_step}
  l2_penalty_coef: ${method.l2_penalty_coef}
  kl_coef: ${method.kl_coef}
  orthogonality_penalty_coef: ${method.orthogonality_penalty_coef}
  encoder_penalty_coef: ${method.encoder_penalty_coef}