defaults:
  - meta_base

name: leo
n_task: 4

# leo specific
kl_coef: 0.001
orthogonality_penalty_coef: 0.1
encoder_penalty_coef: 1.0e-9
leo_inner_lr_init: 1
leo_finetuning_lr_init: 0.001
num_inner_steps: 5
num_finetuning_steps: 5
dropout: 0.3

weight_decay: 1e-5

# LEO (as in MAML) requires special gradient updates in backbone
fast_weight: True

# For instantiate API
cls:
  _target_: methods.leo.LEO
  n_task: ${method.n_task}
  inner_lr_init: ${method.leo_inner_lr_init}
  finetuning_lr_init: ${method.leo_finetuning_lr_init}
  num_inner_steps: ${method.num_inner_steps}
  num_finetuning_steps: ${method.num_finetuning_steps}
  kl_coef: ${method.kl_coef}
  orthogonality_penalty_coef: ${method.orthogonality_penalty_coef}
  encoder_penalty_coef: ${method.encoder_penalty_coef}
  dropout: ${method.dropout}