defaults:
  - meta_base

name: leo
n_task: 4


# leo specific 
l2_penalty_coef: 1.0e-8
kl_coef: 0.001
orthogonality_penalty_coef: 0.1
encoder_penalty_coef: 1.0e-9
leo_inner_lr_init: 1
leo_finetuning_lr_init: 0.001
inner_update_step: 5
finetuning_update_step: 5
dropout: 0.3

# LEO (as in MAML) reqires special gradient updates in backbone
fast_weight: True

# For instantiate API
cls:
  _target_: methods.leo.LEO
  n_task: ${method.n_task}
  inner_lr_init: ${method.leo_inner_lr_init}
  finetuning_lr_init: ${method.leo_finetuning_lr_init}
  inner_update_step: ${method.inner_update_step}
  finetuning_update_step: ${method.finetuning_update_step}
  l2_penalty_coef: ${method.l2_penalty_coef}
  kl_coef: ${method.kl_coef}
  orthogonality_penalty_coef: ${method.orthogonality_penalty_coef}
  encoder_penalty_coef: ${method.encoder_penalty_coef}
  dropout: ${method.dropout}