defaults:
  - dataset: tabula_muris
  - method: maml

model: FCNet
n_way: ???
n_shot: ???
n_query: ???

mode: train

exp:
  name: ???
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: Adam
#lr: 0.001
#Best Swissprot / 1-shot according to validation: 32, 0.0003
#lr: 0.0003
#Best Swissprot / 5-shot according to validation: 64, 0.0001
lr: 0.0001
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

#wandb:
#  project: leo
#  entity: leo
#  mode: "disabled" # Can set to offline, disabled
wandb:
  project: dlclass
  #entity: marblestation
  entity: mstation
  mode: "online"

iter_num: 600
